### ISSUE TITLE
Refactor KeyType

### ISSUE THREAD

**Issue by amika-sq** [TBD54566975/web5-rs#38]
KeyType is confusing. Use what Kotlin does and separate out Algorithm/Curve.

**Comment by decentralgabe** [comment]
Alg/Curve isn't the right abstraction either, unfortunately, since it doesn't cover non-curve key types like RSA or Dilithium.

For example, an RSA JWK would use the `kty` value of `RSA` with no `crv` property. A Dilithium JWK would use the`kty` value `LWE` with no `crv` property, but necessitate the `alg` of `CRYDI5`.

**Comment by decentralgabe** [comment]
I would recommend we either stick to key type or create unique mappings of [alg, crv?, kty] which we can identify [like JOSE does](https://www.iana.org/assignments/jose/jose.xhtml).

**Comment by amika-sq** [comment]
@decentralgabe I was under the impression that Kotlin was doing that unique mappings of alg/kty here:
* [Ed25519](https://github.com/TBD54566975/web5-kt/blob/main/crypto/src/main/kotlin/web5/sdk/crypto/Ed25519.kt#L38-L40)
* [Secp256k1](https://github.com/TBD54566975/web5-kt/blob/main/crypto/src/main/kotlin/web5/sdk/crypto/Secp256k1.kt#L59-L65)

Then the consumer could get at the alg/kty like so: https://github.com/TBD54566975/web5-kt/blob/main/crypto/src/main/kotlin/web5/sdk/crypto/Crypto.kt#L41-L46

Did you have something else in mind here?

**Comment by decentralgabe** [comment]
@amika-sq that abstraction isn't exactly right, since `Ed25519` is a specific usage of the `EdDSA` signature algorithm. The underlying curve, Curve25519 can be used with Ed25519 (EdDSA) or X25519.

Similarly Secp256k1 is bound to a JWA (ES256K), so it does seem like it's chosen a JOSE approach. Secp256k1 can be used for ECDH as well, so keeping it as a 'signer' seems like the wrong abstraction here.

I think something like this might make sense:

- Key Type (Whether curve, octet, lattice, isogency, etc.) (e.g. RSA, Ed25519, Secp256k1)
- Operation and Algorithm pairs e.g. (sign/verify = Ed25519, ECDH = X25519)

[Tink has solved this](https://developers.google.com/tink/supported-key-types) but in a confusing way. Since they refer to key/algorithm pairs as key types. When using JOSE [they differentiate key types](https://developers.google.com/tink/jwt#choosing_a_key_type).

**Comment by amika-sq** [comment]
> So to provide a concrete recommendation, I'd just mimic the abstraction JOSE has.

Could you point me to where that is? Do you mean the Tink abstraction?

**Comment by decentralgabe** [comment]
The section [JSON Web Signature and Encryption Algorithms](https://www.iana.org/assignments/jose/jose.xhtml)

**Comment by KendallWeihe** [comment]
We implement this as `Curve` https://github.com/TBD54566975/web5-rs/blob/807067ec0432478c91d30e391915cb9526c4f583/crates/crypto/src/lib.rs#L27

**Comment by decentralgabe** [comment]
^^ fine for now until we need to support keys that don't use ECC 😄 (no reqs yet but will be eventually with PQC)
